Feature/pokedex-refactored
hex-g/pokedex pull request #3
Opened 2019-05-09 05:05 UTC by SamuelLevi

__( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩__

# New things:
- BCrypt in passwords

# Changes:
- Code style
- Resource name changed ("/admin" removed)
- Final in variables

# Removed:
-

__( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩( ᐛ )و ٩__

2019-05-12 00:15 UTC, eiling commented on src/main/java/hive/pokedex/util/FillNullValues.java
> +  public static void copyProperties(final Object destiny, final Object origin) {
Why (destiny,origin) instead of the (origin,destiny)? Also, source might be better than origin.

2019-05-12 00:52 UTC, eiling approved these changes

2019-05-16 21:17 UTC, manoger requested changes

2019-05-16 21:17 UTC, manoger commented on src/main/java/hive/pokedex/util/FillNullValues.java
> +public final class FillNullValues {
```suggestion
public final class FillerOfNullValues {
```

2019-05-16 22:52 UTC, manoger approved these changes

2019-05-16 22:52 UTC, merged